### ISSUE TITLE
setting body height auto on modal close

### ISSUE THREAD

**Issue by xiio** [adeptoas/sweet-modal#1]
According to: https://github.com/adeptoas/sweet-modal/blob/master/src/js/sweet-modal.coffee#L250

it's really bad idea to set body height to 'auto'. It can in some cases break web app view. IMO better solution is to cache body height onOpen and restore value when onClose happen

**Comment by bluefirex** [comment]
Good point. I'll look into doing that. Thanks for the contribution!

**Comment by bluefirex** [comment]
Setting body height is now removed in v1.2.0.
Thanks for reporting!
