### ISSUE TITLE
Bug when calling an alert immediately after a confirm

### ISSUE THREAD

**Issue by etcho** [adeptoas/sweet-modal#11]
I have a confirm and it's callback does an ajax request, that calls an alert when its complete. On my computer it worked but not on my production server. In production the modal hides, but the overlay element still exists, making impossible to use the page below. After further investigation I discovered that in production the ajax request goes very fast, faster than 300ms. So I changed the close function on SweetModal to remove the overlay after 5ms instead 300ms, and it worked.
Now I don't know the consequences of doing this. I suppose that timeout was there for a reason (it's a typical solution for random problens). Is that a bug? Should I be worried?

**Comment by bluefirex** [comment]
This issue is known. I am working on a solution that might eliminate the need for the timeout function entirely. It's there for animation reasons only, though, so nothing will break if you change it.

**Comment by bluefirex** [comment]
Fixed in edc7e512ea16a354e32034d25eadf22052ca25b4, released in [v1.3.3](https://github.com/adeptoas/sweet-modal/releases/tag/v1.3.3)
