### ISSUE TITLE
close icon not visible in Firefox

### ISSUE THREAD

**Issue by skoften** [adeptoas/sweet-modal#12]
Close icon is not visible in Firefox.

![screen shot 2017-05-25 at 14 43 43](https://cloud.githubusercontent.com/assets/1286410/26450606/9db7cecc-4158-11e7-90d2-617c9a105120.jpg)
![screen shot 2017-05-25 at 14 43 40](https://cloud.githubusercontent.com/assets/1286410/26450607/9de9bc34-4158-11e7-9d5f-ebb71c204de1.jpg)

**Comment by bluefirex** [comment]
Fixed in b0a65d6c8266d4b89abfcce5c00f5b86f445078f, released in [v1.3.3](https://github.com/adeptoas/sweet-modal/releases/tag/v1.3.3)
