### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dev2adventure** [adeptoas/sweet-modal#27]
Sweet Modal don't work. JQuery Version:  3.3.1. Error Code when I use in my  JS Code sweetmodal: Couldn't find sweet-modal in JQuery.js

**Comment by turbopixel** [comment]
> Please bear in mind that the jQuery version of SweetModal is longer actively maintained by me and relies on pull requests. (https://github.com/visma-meglerfront/sweet-modal/issues/26#issuecomment-1058076725)

**Comment by dev2adventure** [comment]
Which JQuery Version is maintained by you? So which JQuery Version should i use?
