### ISSUE TITLE
No margin  at multiline buttons

### ISSUE THREAD

**Issue by SimonMayerhofer** [adeptoas/sweet-modal#6]
See screenshot:

![Screenshot](https://s3.amazonaws.com/f.cl.ly/items/122F2u3F3Y2r0Q2t0E43/Bildschirmfoto%202016-07-15%20um%2011.09.47.JPG)

**Comment by bluefirex** [comment]
Fixed in 967e3a35c277b80bda8bfe787ee70950ea379534, released in [v1.3.3](https://github.com/adeptoas/sweet-modal/releases/tag/v1.3.3)
