### ISSUE TITLE
Sweet not showing

### ISSUE THREAD

**Issue by mmarquez** [adeptoas/sweet-modal#7]
In the function called after prompt I call an ajax function. If I call sweet in the done function nothing is shown.

**Comment by bluefirex** [comment]
Thanks for reporting, fix is in the works!

**Comment by bluefirex** [comment]
Fixed in edc7e512ea16a354e32034d25eadf22052ca25b4, released in [v1.3.3](https://github.com/adeptoas/sweet-modal/releases/tag/v1.3.3)
